### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by schniggie** [uebelack/python-maxcube-api#47]
```
python3 prog.py --host=192.168.178.15 dump
Error processing response message M:
Traceback (most recent call last):
  File "/home/cd/.local/lib/python3.11/site-packages/maxcube/cube.py", line 126, in __parse_responses
    self.parse_m_message(msg.arg)
  File "/home/cd/.local/lib/python3.11/site-packages/maxcube/cube.py", line 167, in parse_m_message
    data = bytearray(base64.b64decode(message.split(",")[2]))
                                      ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[]
```

any idea?

**Comment by Tzaphkiel** [comment]
Yes, like me your message is empty...
But I don't know what that implies...
```
H: ldkf sjldkf jsldkfj sldkfj
M:
C:0cda82,fldksfjg lkdjfg lsdkjfg ldskfjg ldskfgj lsdfkjg sfdklj///////////////////////////dsfgs dfsd fs ///////////////////////////sdlm sldf smdlf smdlf smdlmsdfl ...==                                                       
L:  
```
